name: Build plugin

on:
  release:
    types: [published]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Run build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Strip binary linux
      if: matrix.os == 'ubuntu-latest'
      run: strip target/release/libtinyfiledialogs_deno.so
    - name: Release Plugin
      uses: softprops/action-gh-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
            target/release/libtinyfiledialogs_deno.dylib
            target/release/libtinyfiledialogs_deno.so
            target/release/tinyfiledialogs_deno.dll